services:
  db:
    image: postgis/postgis:15-3.4
    platform: linux/amd64
    container_name: fcp_postgres
    environment:
      POSTGRES_DB: fcp_app_db
      POSTGRES_USER: soukeina
      POSTGRES_PASSWORD: 'soukeina'
      POSTGRES_HOST_AUTH_METHOD: trust 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U soukeina"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    platform: linux/amd64
    container_name: fcp_django
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://soukeina@db:5432/fcp_app_db
      DB_NAME: fcp_app_db
      DB_USER: soukeina
      DB_PASSWORD: soukeina
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: fcp_app_db
      POSTGRES_USER: soukeina
      POSTGRES_PASSWORD: "soukeina"

volumes:
  postgres_data:
  